# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /mcp-shrimp-task-manager

# Install app dependencies
COPY package*.json ./

# Install dependencies without running lifecycle scripts
RUN npm install --ignore-scripts

# Bundle app source code
COPY . .

# Build the TypeScript code
RUN npm run build

# Expose HTTP port for MCP over HTTP and UI port for web interface
EXPOSE 3000 3001

# Default to HTTP mode, but can be overridden
# Use HTTP mode: CMD ["npm", "run", "start:http"]
# Use stdio mode: CMD ["npm", "run", "start"]
ENV HTTP_PORT=3000
ENV WEB_PORT=3001
ENV MODE=http
ENV ENABLE_GUI=true

# Command to run the MCP server in HTTP mode
CMD [ "npm", "run", "start:http" ]
